#Steps Specific Configuration
general:
  buildTool: 'maven'
steps:
  mtaBuild:
    buildTarget: 'NEO'
  neoDeploy:
    neoCredentialsId: 'NEO_DEPLOY'
    account: '123456'
  transportRequestUploadFile:
    applicationId: 'HCP'
